version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes: 
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: WKH73Pv2tK#xa&Q4mH-root
      MYSQL_DATABASE: wordpress_test
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: WKH73Pv2tK#xa&Q4mH
    networks:
      - wpsite
  wp:
    image: wordpress:latest
    ports:
      - 8000:80
    depends_on:
      - mysql
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: WKH73Pv2tK#xa&Q4mH
      WORDPRESS_DB_NAME: wordpress_test
    networks:
      - wpsite
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: WKH73Pv2tK#xa&Q4mH-root
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: